apiVersion: dfaas.dfaas.io/v1
kind: Esperimento
metadata:
  name: test-milano-torino
spec:
  # 1. FEDERATION CONFIGURATION
  federation:
    nodes:
      - nodeID: "milano-edge-01"
        ipAddress: "192.168.252.57"
        username: "isaia"
        password: "root"
        capacity: "MEDIUM"
        balancingStrategy: "staticstrategy"
        privateKey: "MC4CAQAwBQYDK2VwBCIEIODgFN+A8KkNvY8ozKDMXdQV2fehNH43Ba+MYpOzihsJ"
        functions:
          - name: "shasum"
            image: "ghcr.io/openfaas/shasum:latest"
            execTimeout: 4
            maxInflight: 400
            timeoutMs: 6000

      - nodeID: "milano-edge-02"
        ipAddress: "192.168.252.58"
        username: "isaia"
        password: "root"
        capacity: "MEDIUM"
        balancingStrategy: "staticstrategy"
        privateKey: "MC4CAQAwBQYDK2VwBCIEIDK425yPPtvEbZB2ZED5wp2YLn32qmS5Ip5aQzuODfyj"
        functions:
          - name: "shasum"
            image: "ghcr.io/openfaas/shasum:latest"
            execTimeout: 4
            maxInflight: 400
            timeoutMs: 6000
          - name: "figlet"
            image: "ghcr.io/openfaas/figlet:latest"
            execTimeout: 4
            maxInflight: 400
            timeoutMs: 6000

      - nodeID: "milano-edge-03"
        ipAddress: "192.168.252.59"
        username: "isaia"
        password: "root"
        capacity: "MEDIUM"
        balancingStrategy: "staticstrategy"
        privateKey: "MC4CAQAwBQYDK2VwBCIEIH2bNnEMT85rlwCD5bHGqjYbaOW8xOrbVfi8MGsEWjDG"
        functions:
          - name: "figlet"
            image: "ghcr.io/openfaas/figlet:latest"
            execTimeout: 4
            maxInflight: 400
            timeoutMs: 6000

  # 2. NETWORK TOPOLOGY
  topology:
    links:
      - nodeA: "milano-edge-01"
        nodeB: "torino-edge-02"
        latencyMs: 54
      - nodeA: "milano-edge-01"
        nodeB: "torino-edge-03"
        latencyMs: 21

  # 3. CLEANUP FLAG
  isCleanupRequested: false
