apiVersion: dfaas.dfaas.io/v1
kind: Esperimento
metadata:
  name: test-milano-torino
spec:
  # 1. METRICHE
  metrics:
    - step:
        5 # Nota: nella CRD è un INT, quindi metti solo il numero (secondi),
        #si può cabiare il formato a 5s tipo
      metrics:
        - query: "node_cpu_seconds_total"
          comment: "CPU totale consumata dai pod DFaaS"

  # 2. FEDERAZIONE
  federation:
    strategia: "NODE_MARGIN"
    nodi:
      - idNodo: "milano-edge-01"
        indirizzoIP: "192.168.64.3"
        tipoNodo: "MEDIUM"
        funzioni: ["image-proc", "face-det", "figlet"]

  # 3. PROFILO CARICO
  loadProfile:
    commonHeaders: "'Content-Type':'text/plain'"
    scenari:
      - nomeScenario: "test-carico-principale"
        targetNodeID: "milano-edge-01"
        nomeFunzioneTarget: "figlet"
        body: "test carico da venticinque"
        esecutore: "RAMPING_ARRIVAL_RATE"
        vuAllocati: 100
        stages:
          - durata: "15s"
            targetRps: 10
          - durata: "30s"
            targetRps: 50
          - durata: "15s"
            targetRps: 0
