//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurazioneFederazione) DeepCopyInto(out *ConfigurazioneFederazione) {
	*out = *in
	if in.Nodi != nil {
		in, out := &in.Nodi, &out.Nodi
		*out = make([]ConfigurazioneNodo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurazioneFederazione.
func (in *ConfigurazioneFederazione) DeepCopy() *ConfigurazioneFederazione {
	if in == nil {
		return nil
	}
	out := new(ConfigurazioneFederazione)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurazioneNodo) DeepCopyInto(out *ConfigurazioneNodo) {
	*out = *in
	if in.Funzioni != nil {
		in, out := &in.Funzioni, &out.Funzioni
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Vicini != nil {
		in, out := &in.Vicini, &out.Vicini
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurazioneNodo.
func (in *ConfigurazioneNodo) DeepCopy() *ConfigurazioneNodo {
	if in == nil {
		return nil
	}
	out := new(ConfigurazioneNodo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurazoneMetrica) DeepCopyInto(out *ConfigurazoneMetrica) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurazoneMetrica.
func (in *ConfigurazoneMetrica) DeepCopy() *ConfigurazoneMetrica {
	if in == nil {
		return nil
	}
	out := new(ConfigurazoneMetrica)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Esperimento) DeepCopyInto(out *Esperimento) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Esperimento.
func (in *Esperimento) DeepCopy() *Esperimento {
	if in == nil {
		return nil
	}
	out := new(Esperimento)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Esperimento) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsperimentoList) DeepCopyInto(out *EsperimentoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Esperimento, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsperimentoList.
func (in *EsperimentoList) DeepCopy() *EsperimentoList {
	if in == nil {
		return nil
	}
	out := new(EsperimentoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsperimentoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsperimentoSpec) DeepCopyInto(out *EsperimentoSpec) {
	*out = *in
	if in.Metriche != nil {
		in, out := &in.Metriche, &out.Metriche
		*out = make([]ConfigurazoneMetrica, len(*in))
		copy(*out, *in)
	}
	in.Federazione.DeepCopyInto(&out.Federazione)
	in.Profilo.DeepCopyInto(&out.Profilo)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsperimentoSpec.
func (in *EsperimentoSpec) DeepCopy() *EsperimentoSpec {
	if in == nil {
		return nil
	}
	out := new(EsperimentoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsperimentoStatus) DeepCopyInto(out *EsperimentoStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsperimentoStatus.
func (in *EsperimentoStatus) DeepCopy() *EsperimentoStatus {
	if in == nil {
		return nil
	}
	out := new(EsperimentoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfiloCarico) DeepCopyInto(out *ProfiloCarico) {
	*out = *in
	if in.Scenari != nil {
		in, out := &in.Scenari, &out.Scenari
		*out = make([]Scenario, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfiloCarico.
func (in *ProfiloCarico) DeepCopy() *ProfiloCarico {
	if in == nil {
		return nil
	}
	out := new(ProfiloCarico)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scenario) DeepCopyInto(out *Scenario) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]StageK6, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scenario.
func (in *Scenario) DeepCopy() *Scenario {
	if in == nil {
		return nil
	}
	out := new(Scenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StageK6) DeepCopyInto(out *StageK6) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StageK6.
func (in *StageK6) DeepCopy() *StageK6 {
	if in == nil {
		return nil
	}
	out := new(StageK6)
	in.DeepCopyInto(out)
	return out
}
