//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Esperimento) DeepCopyInto(out *Esperimento) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Esperimento.
func (in *Esperimento) DeepCopy() *Esperimento {
	if in == nil {
		return nil
	}
	out := new(Esperimento)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Esperimento) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsperimentoList) DeepCopyInto(out *EsperimentoList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Esperimento, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsperimentoList.
func (in *EsperimentoList) DeepCopy() *EsperimentoList {
	if in == nil {
		return nil
	}
	out := new(EsperimentoList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EsperimentoList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsperimentoSpec) DeepCopyInto(out *EsperimentoSpec) {
	*out = *in
	in.Federazione.DeepCopyInto(&out.Federazione)
	in.Topologia.DeepCopyInto(&out.Topologia)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsperimentoSpec.
func (in *EsperimentoSpec) DeepCopy() *EsperimentoSpec {
	if in == nil {
		return nil
	}
	out := new(EsperimentoSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EsperimentoStatus) DeepCopyInto(out *EsperimentoStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EsperimentoStatus.
func (in *EsperimentoStatus) DeepCopy() *EsperimentoStatus {
	if in == nil {
		return nil
	}
	out := new(EsperimentoStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Federazione) DeepCopyInto(out *Federazione) {
	*out = *in
	if in.Nodi != nil {
		in, out := &in.Nodi, &out.Nodi
		*out = make([]Nodo, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Federazione.
func (in *Federazione) DeepCopy() *Federazione {
	if in == nil {
		return nil
	}
	out := new(Federazione)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FunzioneConfig) DeepCopyInto(out *FunzioneConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FunzioneConfig.
func (in *FunzioneConfig) DeepCopy() *FunzioneConfig {
	if in == nil {
		return nil
	}
	out := new(FunzioneConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Link) DeepCopyInto(out *Link) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Link.
func (in *Link) DeepCopy() *Link {
	if in == nil {
		return nil
	}
	out := new(Link)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Nodo) DeepCopyInto(out *Nodo) {
	*out = *in
	if in.Funzioni != nil {
		in, out := &in.Funzioni, &out.Funzioni
		*out = make([]FunzioneConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Nodo.
func (in *Nodo) DeepCopy() *Nodo {
	if in == nil {
		return nil
	}
	out := new(Nodo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Topologia) DeepCopyInto(out *Topologia) {
	*out = *in
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]Link, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Topologia.
func (in *Topologia) DeepCopy() *Topologia {
	if in == nil {
		return nil
	}
	out := new(Topologia)
	in.DeepCopyInto(out)
	return out
}
