# permissions for end users to edit esperimentos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: dfaas-operator
    app.kubernetes.io/managed-by: kustomize
  name: esperimento-editor-role
rules:
- apiGroups:
  - dfaas.dfaas.io
  resources:
  - esperimentos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dfaas.dfaas.io
  resources:
  - esperimentos/status
  verbs:
  - get
