---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  - persistentvolumeclaims
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dfaas.dfaas.io
  resources:
  - esperimentos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dfaas.dfaas.io
  resources:
  - esperimentos/finalizers
  verbs:
  - update
- apiGroups:
  - dfaas.dfaas.io
  resources:
  - esperimentos/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - k6.io
  resources:
  - testruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k6.io
  resources:
  - testruns/status
  verbs:
  - get
