apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
spec:
  selector:
    app: prometheus # Deve combaciare con la label del Deployment
  ports:
    - protocol: TCP
      port: 9090      # Porta interna del Service
      targetPort: 9090 # Porta su cui ascolta il Pod
      nodePort: 30090  # Porta esterna (IP-VM:30090)
  type: NodePort